export const DIRECTORY_CHANGE_TYPE_CARD = 'DIRECTORY_CHANGE_TYPE_CARD';
export const DIRECTORY_CHANGE_ORDER = 'DIRECTORY_CHANGE_ORDER';
export const DIRECTORY_TOOGLE_PANEL = 'DIRECTORY_TOOGLE_PANEL';
export const DIRECTORY_SEARCH = 'DIRECTORY_SEARCH';
