export const DIRECTORY_CHANGE_TYPE_CARD = 'DIRECTORY_CHANGE_TYPE_CARD';
export const DIRECTORY_CHANGE_ORDER = 'DIRECTORY_CHANGE_ORDER';
export const DIRECTORY_LOAD_CONTACTS = 'DIRECTORY_LOAD_CONTACTS';
export const DIRECTORY_LOAD_CONTACTS_SUCCESS = 'DIRECTORY_LOAD_CONTACTS_SUCCESS';
export const DIRECTORY_LOAD_CONTACTS_FAILURE = 'DIRECTORY_LOAD_CONTACTS_FAILURE';
