export const CONTACT_DETAIL_LOAD_REQUEST = 'CONTACT_DETAIL_LOAD_REQUEST';
export const CONTACT_DETAIL_LOAD_SUCCESS = 'CONTACT_DETAIL_LOAD_SUCCESS';
export const CONTACT_DETAIL_LOAD_FAILURE = 'CONTACT_DETAIL_LOAD_FAILURE';
export const CONTACT_DETAIL_UPDATE = 'CONTACT_DETAIL_UPDATE';
