export const CONTACT_UPDATED = 'CONTACT_UPDATED';
export const CONTACT_SUBMITTED = 'CONTACT_SUBMITTED';
export const CONTACT_DELETE_REQUEST = 'CONTACT_DELETE_REQUEST';
export const CONTACT_DELETE_SUCCESS = 'CONTACT_DELETE_SUCCESS';
export const CONTACT_DELETE_FAILURE = 'CONTACT_DELETE_FAILURE';
export const CONTACT_LOAD_REQUEST = 'CONTACT_LOAD_REQUEST';
export const CONTACT_LOAD_SUCCESS = 'CONTACT_LOAD_SUCCESS';
export const CONTACT_LOAD_FAILURE = 'CONTACT_LOAD_FAILURE';

